config/routes.rb
Varophone::Application.routes.draw do


  authenticated :user do
    namespace :admin do
      resources :users
      resources :pbx_users
      resources :pbx_user_groups
      resources :phone_numbers
      resources :devices
      match :dashboard, to: "dashboard#index", as: "dashboard", via:[:get, :post]
      resources :extensions
      resources :extension_lines
      resources :extension_ring_groups
      resources :extension_conference_rooms
      resources :extension_call_queues
      resources :extension_dial_plans
      resources :extension_shared_voicemail_boxes
      resources :extension_virtual_fax_machines
      match :extension_lines_index, to: "extensions#extension_lines", via:[:get, :post, :put]
      match :extension_ring_groups_index, to: "extensions#extension_ring_groups", via:[:get, :post, :get]
      match :extension_conference_rooms_index, to: "extensions#extension_conference_rooms", via:[:get, :post, :get]
      match :extension_call_queues_index, to: "extensions#extension_call_queues", via:[:get, :post, :get]
      match :extension_dial_plans_index, to: "extensions#extension_dial_plans", via:[:get, :post, :get]
      match :extension_shared_voicemail_boxes_index, to: "extensions#extension_shared_voicemail_boxes", via:[:get, :post, :get]
      match :extension_virtual_fax_machines_index, to: "extensions#extension_virtual_fax_machines", via:[:get, :post, :get]
      resources :corporate_directories
      resources :paging_profiles
      resources :device_buttons
    end

    namespace :super_admin do
      resources :pbxes
      resources :pbx_users
      resources :pbx_user_groups
      resources :phone_numbers
      resources :users
      resources :devices
      match :dashboard, to: "dashboard#index", as: "dashboard", via:[:get]
    end

    root :to => 'home#dashboard'
  end

  root :to => "home#index"
  devise_for :users
  resources :users
  # un comment the following line after development
  #match "*path" => 'error#handle404'
end

app/models/paging_profile.rb
class PagingProfile < ActiveRecord::Base
  attr_accessible :name, :off_hook_paging_interrupt, :paging_realm
end

app/controllers/paging_profiles_controller.rb
class PagingProfilesController < ApplicationController
  # GET /paging_profiles
  # GET /paging_profiles.json
  def index
    @paging_profiles = PagingProfile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @paging_profiles }
    end
  end

  # GET /paging_profiles/1
  # GET /paging_profiles/1.json
  def show
    @paging_profile = PagingProfile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @paging_profile }
    end
  end

  # GET /paging_profiles/new
  # GET /paging_profiles/new.json
  def new
    @paging_profile = PagingProfile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paging_profile }
    end
  end

  # GET /paging_profiles/1/edit
  def edit
    @paging_profile = PagingProfile.find(params[:id])
  end

  # POST /paging_profiles
  # POST /paging_profiles.json
  def create
    @paging_profile = PagingProfile.new(params[:paging_profile])

    respond_to do |format|
      if @paging_profile.save
        format.html { redirect_to @paging_profile, notice: 'Paging profile was successfully created.' }
        format.json { render json: @paging_profile, status: :created, location: @paging_profile }
      else
        format.html { render action: "new" }
        format.json { render json: @paging_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /paging_profiles/1
  # PUT /paging_profiles/1.json
  def update
    @paging_profile = PagingProfile.find(params[:id])

    respond_to do |format|
      if @paging_profile.update_attributes(params[:paging_profile])
        format.html { redirect_to @paging_profile, notice: 'Paging profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @paging_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paging_profiles/1
  # DELETE /paging_profiles/1.json
  def destroy
    @paging_profile = PagingProfile.find(params[:id])
    @paging_profile.destroy

    respond_to do |format|
      format.html { redirect_to paging_profiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/paging_profiles_helper.rb
module PagingProfilesHelper
end

app/views/paging_profiles/_form.html.haml
= form_for @paging_profile do |f|
  - if @paging_profile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@paging_profile.errors.count, "error")} prohibited this paging_profile from being saved:"
      %ul
        - @paging_profile.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :off_hook_paging_interrupt
    = f.check_box :off_hook_paging_interrupt
  .field
    = f.label :paging_realm
    = f.text_field :paging_realm
  .actions
    = f.submit 'Save'

app/views/paging_profiles/edit.html.haml
%h1 Editing paging_profile

= render 'form'

= link_to 'Show', @paging_profile
\|
= link_to 'Back', paging_profiles_path

app/views/paging_profiles/index.html.haml
%h1 Listing paging_profiles

%table
  %tr
    %th Name
    %th Off hook paging interrupt
    %th Paging realm
    %th
    %th
    %th

  - @paging_profiles.each do |paging_profile|
    %tr
      %td= paging_profile.name
      %td= paging_profile.off_hook_paging_interrupt
      %td= paging_profile.paging_realm
      %td= link_to 'Show', paging_profile
      %td= link_to 'Edit', edit_paging_profile_path(paging_profile)
      %td= link_to 'Destroy', paging_profile, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Paging profile', new_paging_profile_path

app/views/paging_profiles/new.html.haml
%h1 New paging_profile

= render 'form'

= link_to 'Back', paging_profiles_path

app/views/paging_profiles/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @paging_profile.name
%p
  %b Off hook paging interrupt:
  = @paging_profile.off_hook_paging_interrupt
%p
  %b Paging realm:
  = @paging_profile.paging_realm

= link_to 'Edit', edit_paging_profile_path(@paging_profile)
\|
= link_to 'Back', paging_profiles_path