config/routes.rb
Varophone::Application.routes.draw do


  authenticated :user do
    namespace :admin do
      resources :users
      resources :pbx_users
      resources :pbx_user_groups
      resources :phone_numbers
      resources :devices
      match :dashboard, to: "dashboard#index", as: "dashboard", via:[:get, :post]
      resources :extensions
      resources :extension_lines
      resources :extension_ring_groups
      resources :extension_conference_rooms
      resources :extension_call_queues
      resources :extension_dial_plans
      resources :extension_shared_voicemail_boxes
      resources :extension_virtual_fax_machines
      match :extension_lines_index, to: "extensions#extension_lines", via:[:get, :post, :put]
      match :extension_ring_groups_index, to: "extensions#extension_ring_groups", via:[:get, :post, :get]
      match :extension_conference_rooms_index, to: "extensions#extension_conference_rooms", via:[:get, :post, :get]
      match :extension_call_queues_index, to: "extensions#extension_call_queues", via:[:get, :post, :get]
      match :extension_dial_plans_index, to: "extensions#extension_dial_plans", via:[:get, :post, :get]
      match :extension_shared_voicemail_boxes_index, to: "extensions#extension_shared_voicemail_boxes", via:[:get, :post, :get]
      match :extension_virtual_fax_machines_index, to: "extensions#extension_virtual_fax_machines", via:[:get, :post, :get]
      resources :corporate_directories
      resources :paging_profiles
      resources :device_buttons
    end

    namespace :super_admin do
      resources :pbxes
      resources :pbx_users
      resources :pbx_user_groups
      resources :phone_numbers
      resources :users
      resources :devices
      match :dashboard, to: "dashboard#index", as: "dashboard", via:[:get]
    end

    root :to => 'home#dashboard'
  end

  root :to => "home#index"
  devise_for :users
  resources :users
  # un comment the following line after development
  #match "*path" => 'error#handle404'
end

app/models/dashboard.rb
class Dashboard

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController
  def index
    if params[:pbx_id].present?
      session[:pbx_id] = params[:pbx_id]
      @pbx = Pbx.find(params[:pbx_id])
    elsif session[:pbx_id].present?
      @pbx = Pbx.find(session[:pbx_id])
    else 
      # TODO: Might need to think of a better way to handle missing pbx_id parameter.
      @pbx = Pbx.new
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/super_admin/dashboard_controller.rb
class SuperAdmin::DashboardController < SuperAdminController
  def index
    @pbxes = current_user.pbxes
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/admin/dashboard/index.html.haml
= render "layouts/phone_admin_sidebar"
%h1= @pbx.name

%p Find me in app/views/dashboard/index.html.haml

%p This will be the main administration page for a given PBX

%p This would be a great place for some CDR or something:

.row
  .span3
    = link_to new_admin_pbx_user_path, :class => 'well' do
      %h3.well-title
        %i{:class => 'icon-user-add'}
        Add a User
      %hr.well-divider
        .well-content
          Add new users for the PBX.
  .span3
    = link_to new_admin_device_path, :class => 'well' do
      %h3.well-title
        %i{:class => 'icon-phone-alt'}
        Add a Device
      %hr.well-divider
        .well-content
          Add devices to the PBX.