config/routes.rb
Varophone::Application.routes.draw do


  authenticated :user do
    namespace :admin do
      resources :users
      resources :pbx_users
      resources :pbx_user_groups
      resources :phone_numbers
      resources :devices
      match :dashboard, to: "dashboard#index", as: "dashboard", via:[:get, :post]
      resources :extensions
      resources :extension_lines
      resources :extension_ring_groups
      resources :extension_conference_rooms
      resources :extension_call_queues
      resources :extension_dial_plans
      resources :extension_shared_voicemail_boxes
      resources :extension_virtual_fax_machines
      match :extension_lines_index, to: "extensions#extension_lines", via:[:get, :post, :put]
      match :extension_ring_groups_index, to: "extensions#extension_ring_groups", via:[:get, :post, :get]
      match :extension_conference_rooms_index, to: "extensions#extension_conference_rooms", via:[:get, :post, :get]
      match :extension_call_queues_index, to: "extensions#extension_call_queues", via:[:get, :post, :get]
      match :extension_dial_plans_index, to: "extensions#extension_dial_plans", via:[:get, :post, :get]
      match :extension_shared_voicemail_boxes_index, to: "extensions#extension_shared_voicemail_boxes", via:[:get, :post, :get]
      match :extension_virtual_fax_machines_index, to: "extensions#extension_virtual_fax_machines", via:[:get, :post, :get]
      resources :corporate_directories
      resources :paging_profiles
      resources :device_buttons
    end

    namespace :super_admin do
      resources :pbxes
      resources :pbx_users
      resources :pbx_user_groups
      resources :phone_numbers
      resources :users
      resources :devices
      match :dashboard, to: "dashboard#index", as: "dashboard", via:[:get]
    end

    root :to => 'home#dashboard'
  end

  root :to => "home#index"
  devise_for :users
  resources :users
  # un comment the following line after development
  #match "*path" => 'error#handle404'
end

app/models/pbx_user_group.rb
class PbxUserGroup < ActiveRecord::Base
  belongs_to :pbx
  has_and_belongs_to_many :pbx_users

  attr_accessible :domestic_long_distance_access, :eavesdropping_access, :internal_access, :international_access, :local_access, :malicious_area_codes_access, :name, :prompt_recording_access, :super_access, :toll_numbers_access

  def members
    users = pbx_users.map(&:full_name).join ", "
  end
end

app/controllers/admin/pbx_user_groups_controller.rb
class Admin::PbxUserGroupsController < AdminController
  # GET /pbx_user_groups
  # GET /pbx_user_groups.json
  def index
    @pbx_user_groups = PbxUserGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pbx_user_groups }
    end
  end

  # GET /pbx_user_groups/1
  # GET /pbx_user_groups/1.json
  def show
    @pbx_user_group = PbxUserGroup.find(params[:id])
    @members = @pbx_user_group.members

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pbx_user_group }
    end
  end

  # GET /pbx_user_groups/new
  # GET /pbx_user_groups/new.json
  def new
    @pbx_user_group = PbxUserGroup.new
    @members = @pbx_user_group.pbx_users

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pbx_user_group }
    end
  end

  # GET /pbx_user_groups/1/edit
  def edit
    @pbx_user_group = PbxUserGroup.find(params[:id])
    @members = @pbx_user_group.pbx_users
  end

  # POST /pbx_user_groups
  # POST /pbx_user_groups.json
  def create
    @pbx_user_group = PbxUserGroup.new(params[:pbx_user_group])

    respond_to do |format|
      if @pbx_user_group.save
        format.html { redirect_to @pbx_user_group, notice: 'Pbx user group was successfully created.' }
        format.json { render json: @pbx_user_group, status: :created, location: @pbx_user_group }
      else
        format.html { render action: "new" }
        format.json { render json: @pbx_user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pbx_user_groups/1
  # PUT /pbx_user_groups/1.json
  def update
    @pbx_user_group = PbxUserGroup.find(params[:id])

    respond_to do |format|
      if @pbx_user_group.update_attributes(params[:pbx_user_group])
        format.html { redirect_to @pbx_user_group, notice: 'Pbx user group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pbx_user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pbx_user_groups/1
  # DELETE /pbx_user_groups/1.json
  def destroy
    @pbx_user_group = PbxUserGroup.find(params[:id])
    @pbx_user_group.destroy

    respond_to do |format|
      format.html { redirect_to pbx_user_groups_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/super_admin/pbx_user_groups_controller.rb
class SuperAdmin::PbxUserGroupsController < SuperAdminController
  # GET /pbx_user_groups
  # GET /pbx_user_groups.json
  def index
    @pbx_user_groups = PbxUserGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pbx_user_groups }
    end
  end

  # GET /pbx_user_groups/1
  # GET /pbx_user_groups/1.json
  def show
    @pbx_user_group = PbxUserGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pbx_user_group }
    end
  end

  # GET /pbx_user_groups/new
  # GET /pbx_user_groups/new.json
  def new
    @pbx_user_group = PbxUserGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pbx_user_group }
    end
  end

  # GET /pbx_user_groups/1/edit
  def edit
    @pbx_user_group = PbxUserGroup.find(params[:id])
  end

  # POST /pbx_user_groups
  # POST /pbx_user_groups.json
  def create
    @pbx_user_group = PbxUserGroup.new(params[:pbx_user_group])

    respond_to do |format|
      if @pbx_user_group.save
        format.html { redirect_to @pbx_user_group, notice: 'Pbx user group was successfully created.' }
        format.json { render json: @pbx_user_group, status: :created, location: @pbx_user_group }
      else
        format.html { render action: "new" }
        format.json { render json: @pbx_user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pbx_user_groups/1
  # PUT /pbx_user_groups/1.json
  def update
    @pbx_user_group = PbxUserGroup.find(params[:id])

    respond_to do |format|
      if @pbx_user_group.update_attributes(params[:pbx_user_group])
        format.html { redirect_to @pbx_user_group, notice: 'Pbx user group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pbx_user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pbx_user_groups/1
  # DELETE /pbx_user_groups/1.json
  def destroy
    @pbx_user_group = PbxUserGroup.find(params[:id])
    @pbx_user_group.destroy

    respond_to do |format|
      format.html { redirect_to pbx_user_groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pbx_user_groups_helper.rb
module PbxUserGroupsHelper
end

app/views/admin/pbx_user_groups/_form.html.haml
= form_for [:admin, @pbx_user_group] do |f|
  .form-horizontal
    - if @pbx_user_group.errors.any?
      #error_explanation
        %h2= "#{pluralize(@pbx_user_group.errors.count, "error")} prohibited this pbx_user_group from being saved:"
        %ul
          - @pbx_user_group.errors.full_messages.each do |msg|
            %li= msg

    = f.hidden_field :pbx, value: @pbx.id

    %ul.nav.nav-tabs
      %li.active
        =link_to "#general-tab", data: { toggle: 'tab' } do
          General
      %li
        = link_to "#members-tab", data: { toggle: 'tab'} do
          Members
    .tab-content
      #general-tab.tab-pane.active
        .control-group
          .control-label
            = f.label :name
          .controls
            = f.text_field :name
        .row
          .span4
            .control-group
              .control-label
                = f.label :internal_access
              .controls
                = f.check_box :internal_access
              .control-label  
                .help-block
                  Allows dialing of internal extensions.
            .control-group
              .control-label
                = f.label :local_access
              .controls
                = f.check_box :local_access
              .control-label  
                .help-block
                  Allows dialing of local phone numbers.
            .control-group
              .control-label
                = f.label :domestic_long_distance_access
              .controls
                = f.check_box :domestic_long_distance_access
              .control-label  
                .help-block
                  Allows domestic long distance dialing.
            .control-group
              .control-label
                = f.label :international_access
              .controls
                = f.check_box :international_access
              .control-label  
                .help-block
                  Allows dialing of international phone numbers.
            .control-group
              .control-label
                = f.label :toll_numbers_access
              .controls
                = f.check_box :toll_numbers_access
              .control-label  
                .help-block
                  Allows dialing of Toll Numbers.
          .span4
            .control-group
              .control-label
                = f.label :malicious_area_codes_access
              .controls
                = f.check_box :malicious_area_codes_access
              .control-label  
                .help-block
                  Allows dialing to areas know to be malicious.
            .control-group
              .control-label
                = f.label :super_access
              .controls
                = f.check_box :super_access
              .control-label  
                .help-block
                  Access to modify all system params.
            .control-group
              .control-label
                = f.label :eavesdropping_access
              .controls
                = f.check_box :eavesdropping_access
              .control-label  
                .help-block
                  Allows eavesdropping on other calls. 
            .control-group
              .control-label
                = f.label :prompt_recording_access
              .controls
                = f.check_box :prompt_recording_access
              .control-label  
                .help-block
                  Allows user to record voicemail prompts for the system. 
        .controls
          = f.submit 'Save', class: "btn btn-primary"
      #members-tab.tab-pane
        %h3= @pbx_user_group.name
        %p
          %h6 Group Members:
        %ul.well
          - @members.each do |member|
            %li= member.full_name
          %br
          = link_to "Add User to Group", 'add_new_member'
          / TODO: Create modal to add user to a Group

app/views/admin/pbx_user_groups/edit.html.haml
%h3 Edit User Group for:
%h1= @pbx.name
%br
= render 'layouts/phone_admin_sidebar'
= render 'form'

= link_to 'Back', admin_pbx_user_groups_path

app/views/admin/pbx_user_groups/index.html.haml
=render "layouts/phone_admin_sidebar"
%h3 PBX User Groups for:
%h1= @pbx.name

- @pbx_user_groups.each do |pbx_user_group|
  .row
    .span8
      = link_to admin_pbx_user_group_path(pbx_user_group), :method => :delete, :data => { :confirm => 'Are you sure?' } do
        .well-title.pull-right 
          %i{class: 'icon-remove-2', style: "margin-top:15px;"}

      = link_to edit_admin_pbx_user_group_path(pbx_user_group), :class => 'well' do
        %h3.well-title
          %i{:class => 'icon-group'}
          = pbx_user_group.name
        %hr.well-divider
        .well-content
          = "Members: " + pbx_user_group.members
          .pull-right
            Other information
= link_to 'New Pbx user group', new_admin_pbx_user_group_path

app/views/admin/pbx_user_groups/new.html.haml
%h1 New pbx_user_group
= render 'layouts/phone_admin_sidebar'

= render 'form'

= link_to 'Back', admin_pbx_user_groups_path