config/routes.rb
Varophone::Application.routes.draw do


  authenticated :user do
    namespace :admin do
      resources :users
      resources :pbx_users
      resources :pbx_user_groups
      resources :phone_numbers
      resources :devices
      match :dashboard, to: "dashboard#index", as: "dashboard", via:[:get, :post]
      resources :extensions
      resources :extension_lines
      resources :extension_ring_groups
      resources :extension_conference_rooms
      resources :extension_call_queues
      resources :extension_dial_plans
      resources :extension_shared_voicemail_boxes
      resources :extension_virtual_fax_machines
      match :extension_lines_index, to: "extensions#extension_lines", via:[:get, :post, :put]
      match :extension_ring_groups_index, to: "extensions#extension_ring_groups", via:[:get, :post, :get]
      match :extension_conference_rooms_index, to: "extensions#extension_conference_rooms", via:[:get, :post, :get]
      match :extension_call_queues_index, to: "extensions#extension_call_queues", via:[:get, :post, :get]
      match :extension_dial_plans_index, to: "extensions#extension_dial_plans", via:[:get, :post, :get]
      match :extension_shared_voicemail_boxes_index, to: "extensions#extension_shared_voicemail_boxes", via:[:get, :post, :get]
      match :extension_virtual_fax_machines_index, to: "extensions#extension_virtual_fax_machines", via:[:get, :post, :get]
      resources :corporate_directories
      resources :paging_profiles
      resources :device_buttons
    end

    namespace :super_admin do
      resources :pbxes
      resources :pbx_users
      resources :pbx_user_groups
      resources :phone_numbers
      resources :users
      resources :devices
      match :dashboard, to: "dashboard#index", as: "dashboard", via:[:get]
    end

    root :to => 'home#dashboard'
  end

  root :to => "home#index"
  devise_for :users
  resources :users
  # un comment the following line after development
  #match "*path" => 'error#handle404'
end

app/models/pbx_user.rb
class PbxUser < ActiveRecord::Base
  belongs_to :pbx
  belongs_to :sysadmin_user #add class User and foreign key here to tie to user table
  has_and_belongs_to_many :pbx_user_groups

  attr_accessible :dialable_username, :dialable_password, :email, :first_name, :last_name, :sysadmin_login_enabled, :pbx_id, :sysadmin_user_id

  def full_name
    "#{first_name} #{last_name}"
  end

  def sysadmin_yes_no
    if sysadmin_login_enabled?
      "Yes"
    else
      "No"
    end
  end

end

app/controllers/admin/pbx_users_controller.rb
class Admin::PbxUsersController < AdminController
  # GET /pbx_users
  # GET /pbx_users.json
  def index
    @pbx_users = PbxUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pbx_users }
    end
  end

  # GET /pbx_users/1
  # GET /pbx_users/1.json
  def show
    @pbx_user = PbxUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pbx_user }
    end
  end

  # GET /pbx_users/new
  # GET /pbx_users/new.json
  def new
    @pbx_user = PbxUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pbx_user }
    end
  end

  # GET /pbx_users/1/edit
  def edit
    @pbx_user = PbxUser.find(params[:id])
    @groups = @pbx_user.pbx_user_groups
  end

  # POST /pbx_users
  # POST /pbx_users.json
  def create
    @pbx_user = PbxUser.new(params[:pbx_user])

    respond_to do |format|
      if @pbx_user.save
        format.html { redirect_to edit_admin_pbx_user_path(@pbx_user), notice: 'Pbx user was successfully created.' }
        format.json { render json: @pbx_user, status: :created, location: @pbx_user }
      else
        format.html { render action: "new" }
        format.json { render json: @pbx_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pbx_users/1
  # PUT /pbx_users/1.json
  def update
    @pbx_user = PbxUser.find(params[:id])

    respond_to do |format|
      if @pbx_user.update_attributes(params[:pbx_user])
        format.html { redirect_to edit_admin_pbx_user_path(@pbx_user), notice: 'Pbx user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pbx_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pbx_users/1
  # DELETE /pbx_users/1.json
  def destroy
    @pbx_user = PbxUser.find(params[:id])
    @pbx_user.destroy

    respond_to do |format|
      format.html { redirect_to admin_pbx_users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/super_admin/pbx_users_controller.rb
class SuperAdmin::PbxUsersController < SuperAdminController
  # GET /pbx_users
  # GET /pbx_users.json
  def index
    @pbx_users = PbxUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pbx_users }
    end
  end

  # GET /pbx_users/1
  # GET /pbx_users/1.json
  def show
    @pbx_user = PbxUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pbx_user }
    end
  end

  # GET /pbx_users/new
  # GET /pbx_users/new.json
  def new
    @pbx_user = PbxUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pbx_user }
    end
  end

  # GET /pbx_users/1/edit
  def edit
    @pbx_user = PbxUser.find(params[:id])
  end

  # POST /pbx_users
  # POST /pbx_users.json
  def create
    @pbx_user = PbxUser.new(params[:pbx_user])

    respond_to do |format|
      if @pbx_user.save
        format.html { redirect_to @pbx_user, notice: 'Pbx user was successfully created.' }
        format.json { render json: @pbx_user, status: :created, location: @pbx_user }
      else
        format.html { render action: "new" }
        format.json { render json: @pbx_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pbx_users/1
  # PUT /pbx_users/1.json
  def update
    @pbx_user = PbxUser.find(params[:id])

    respond_to do |format|
      if @pbx_user.update_attributes(params[:pbx_user])
        format.html { redirect_to @pbx_user, notice: 'Pbx user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pbx_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pbx_users/1
  # DELETE /pbx_users/1.json
  def destroy
    @pbx_user = PbxUser.find(params[:id])
    @pbx_user.destroy

    respond_to do |format|
      format.html { redirect_to pbx_users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pbx_users_helper.rb
module PbxUsersHelper
end

app/views/admin/pbx_users/_form.html.haml
= form_for [:admin, @pbx_user] do |f|
  .form-horizontal
    - if @pbx_user.errors.any?
      #error_explanation
        %h2= "#{pluralize(@pbx_user.errors.count, "error")} prohibited this pbx_user from being saved:"
        %ul
          - @pbx_user.errors.full_messages.each do |msg|
            %li= msg

    = f.hidden_field :pbx_id, value: @pbx.id
    %ul.nav.nav-tabs
      %li.active
        =link_to "#general-tab", data: { toggle: 'tab' } do
          General
      %li
        = link_to "#membership-tab", data: { toggle: 'tab'} do
          Group Membership

    .tab-content
      #general-tab.tab-pane.active
        %h6 Identity
        .control-group
          .control-label
            = f.label :first_name
          .controls
            = f.text_field :first_name
        .control-group
          .control-label
            = f.label :last_name
          .controls
            = f.text_field :last_name
        .control-group
          .control-label
            = f.label :email
          .controls
            = f.text_field :email
        .control-group
          .control-label
            = f.label :dialable_username
          .controls
            = f.text_field :dialable_username
        .control-group
          .control-label
            = f.label :sysadmin_login_enabled
          .controls
            = f.check_box :sysadmin_login_enabled
        .control-group
          .control-label
            = f.label :sysadmin_user_id
          .controls
            = f.text_field :sysadmin_user_id
        
        .controls
          = f.submit 'Save', class: "btn btn-primary"

        %hr
        %h6 Password
        .control-group
          .control-label
            = f.label :dialable_password
          .controls
            .input-append
              = f.text_field :dialable_password
              = f.submit 'Change', class: "btn btn-warning"
        %hr
        %h6 User Portal
        %br
        Coming Soon
      #membership-tab.tab-pane
        .well.span6
          - if @groups.present?
            - @groups.each do |group|
              %ul 
                %li= group.name
                = link_to "Add Group", "#"
            / TODO: Add modal to choose different User Group -
          - else
            = link_to "Add Group", "#"
            / TODO: Add modal to choose different User Group - 

app/views/admin/pbx_users/edit.html.haml
%h3 Edit PBX User for:
%h1= @pbx.name
%br
= render 'layouts/phone_admin_sidebar'
= render 'form'

= link_to 'Back', admin_pbx_users_path

app/views/admin/pbx_users/index.html.haml
=render "layouts/phone_admin_sidebar"
%h3 Pbx Users for:
%h1= @pbx.name


%br
- @pbx_users.each do |pbx_user|
  .row
    .span8
      = link_to admin_pbx_user_path(pbx_user), :method => :delete, :data => { :confirm => 'Are you sure?' } do
        .well-title.pull-right 
          %i{class: 'icon-remove-2', style: "margin-top:15px;"}
      = link_to edit_admin_pbx_user_path(pbx_user), :class => 'well' do
        %h3.well-title
          %i{:class => 'icon-user'}
          = pbx_user.full_name
        %hr.well-divider
        .well-content
          = "Email: " + pbx_user.email 
          .pull-right
            = "System Admin:" + pbx_user.sysadmin_yes_no
          %br
          - if pbx_user.dialable_username.present?
            = "Dialable User Name: " + pbx_user.dialable_username  
          - else
            Dialable User Name: n/a
          .pull-right
            Other information
= link_to 'New Pbx user', new_admin_pbx_user_path

app/views/admin/pbx_users/new.html.haml
%h3 New PBX User for:
%h1= @pbx.name
%br
= render 'layouts/phone_admin_sidebar'

= render 'form'

= link_to 'Back', admin_pbx_users_path